version: '3.7'

services:
  pontem-node:
    container_name: pontem-node
    hostname: pontem-node
    restart: always
    #image: pontem/pontem:${PONTEM_VERSION}
    build:
      context: .build
      dockerfile: ${DOCKERFILE} # If you have errors when building or executing, please read the description in the .env.testnet
      args:
        PONTEM_VERSION: ${PONTEM_VERSION}
        DOVE_VERSION: ${DOVE_VERSION}
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "127.0.0.1:9934:9934"   # relaychain rpc
      - "127.0.0.1:9945:9945"   # relaychain ws
      - "30334:30334"           # relaychain p2p
      - "127.0.0.1:9933:9933"   # parachain rpc
      - "127.0.0.1:9944:9944"   # parachain ws
      - "30333:30333"           # parachain p2p
      - "9615:9615"             # prometheus metrics
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    volumes:
      - ./genesis/genesis-raw-relaychain-${GENESIS}.json:/opt/pontem/genesis-relaychain.json
      - ./genesis/genesis-raw-pontem-${GENESIS}.json:/opt/pontem/genesis.json
      - ./data:/opt/pontem/data
      - ./keys:/opt/pontem/keys
    command: pontem --base-path /opt/pontem/data --chain /opt/pontem/genesis.json --keystore-path /opt/pontem/keys --collator --name ${NODE_NAME} --parachain-id 2000 --port 30333 --ws-port 9944 --rpc-port 9933 ${PUBLIC_ADDR_PARACHAIN} ${BOOTNODES_PARACHAIN} --prometheus-external -- --execution wasm --chain /opt/pontem/genesis-relaychain.json --port 30334 --ws-port 9945 --rpc-port 9934 ${PUBLIC_ADDR_RELAYCHAIN} ${BOOTNODES_RELAYCHAIN}
