version: '3.7'

services:
  node-restarter:
    build:
      context: .build
      dockerfile: restarter.Dockerfile
    container_name: node-restarter
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/opt/scripts
    command: bash /opt/scripts/restart-node.sh