{
 "title": "Pontem Node Metrics",
 "tags": [ "pontem" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"pontem-node\"} == bool 1",
     "legendFormat": "Is node up?"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Free storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\"})"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"server\"}",
     "legendFormat": "last 1 minute"
    },
    {
     "expr": "node_load5{job=\"server\"}",
     "legendFormat": " last 5 minutes"
    },
    {
     "expr": "node_load15{job=\"server\"}",
     "legendFormat": "last 15 minutes"
    }
   ]
  },
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "Block Total Tx",
   "type": "stat",
   "description": "Total transactions in best block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Size (bytes)" }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Proposer Block Construction Time",
   "type": "graph",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Time (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "90th quantile for block construction time (s)"
    }
   ]
  }
 ]
}